export const RESPONSE_SUCCESS_CODE = 0;

export const HANDLER_IDS = {
  INITIAL: 0,
  REGISTER: 1,
  LOGIN: 3,
  MATCH: 5,
  SYNC: 7,
  PURCHASE: 8,
  MONSTER_SPAWN: 11,
  TOWER_ATTACK: 14,
  MONSTER_ATTACK: 16,
  GAME_END: 19,
  MONSTER_DEATH: 20,
};
